import { Entry } from "$db/resolver.ts";
import { Item } from "$collections/items/collection.ts";
import { cost, dmg, source } from "$helpers";

const Range = {
  MELEE: { kind: "melee", normal: 5 },
  REACH: { kind: "melee", normal: 10 },
} as const;

export const phbItems: Entry<Item>[] = [
  {
    id: "club",
    name: "Club",
    cost: cost("1 sp"),
    weight: 2,
    kind: "weapon",
    category: "simple",
    range: Range.MELEE,
    damage: dmg("1d4", "bludgeoning"),
    properties: [{ kind: "light" }],
    tags: [],
    source: source("PHB", 149),
  },
  {
    id: "dagger",
    name: "Dagger",
    cost: cost("2 gp"),
    weight: 1,
    kind: "weapon",
    category: "simple",
    range: Range.MELEE,
    damage: dmg("1d4", "piercing"),
    properties: [
      { kind: "light" },
      { kind: "finesse" },
      {
        kind: "thrown",
        thrownRange: { normal: 20, long: 60 },
      },
    ],
    tags: [],
    source: source("PHB", 149),
  },
  {
    id: "greatclub",
    name: "Greatclub",
    cost: cost("2 sp"),
    weight: 10,
    kind: "weapon",
    category: "simple",
    range: Range.MELEE,
    damage: dmg("1d8", "bludgeoning"),
    properties: [{ kind: "twoHanded" }],
    tags: [],
    source: source("PHB", 149),
  },
  {
    id: "handaxe",
    name: "Handaxe",
    cost: cost("5 gp"),
    weight: 2,
    kind: "weapon",
    category: "simple",
    range: Range.MELEE,
    damage: dmg("1d6", "piercing"),
    properties: [
      {
        kind: "thrown",
        thrownRange: { normal: 20, long: 60 },
      },
    ],
    tags: [],
    source: source("PHB", 149),
  },
  {
    id: "handaxe",
    name: "Handaxe",
    cost: cost("5 gp"),
    weight: 2,
    kind: "weapon",
    category: "simple",
    range: Range.MELEE,
    damage: dmg("1d6", "piercing"),
    properties: [
      { kind: "light" },
      {
        kind: "thrown",
        thrownRange: { normal: 20, long: 60 },
      },
    ],
    tags: [],
    source: source("PHB", 149),
  },
  {
    id: "javelin",
    name: "Javelin",
    cost: cost("5 sp"),
    weight: 2,
    kind: "weapon",
    category: "simple",
    range: Range.MELEE,
    damage: dmg("1d6", "piercing"),
    properties: [
      {
        kind: "thrown",
        thrownRange: { normal: 30, long: 120 },
      },
    ],
    tags: [],
    source: source("PHB", 149),
  },
  {
    id: "lightHammer",
    name: "Light hammer",
    cost: cost("2 gp"),
    weight: 2,
    kind: "weapon",
    category: "simple",
    range: Range.MELEE,
    damage: dmg("1d4", "bludgeoning"),
    properties: [
      { kind: "light" },
      {
        kind: "thrown",
        thrownRange: { normal: 20, long: 60 },
      },
    ],
    tags: [],
    source: source("PHB", 149),
  },
  {
    id: "mace",
    name: "Mace",
    cost: cost("5 gp"),
    weight: 4,
    kind: "weapon",
    category: "simple",
    range: Range.MELEE,
    damage: dmg("1d6", "bludgeoning"),
    properties: [],
    tags: [],
    source: source("PHB", 149),
  },
  {
    id: "quarterstaff",
    name: "Quarterstaff",
    cost: cost("2 sp"),
    weight: 4,
    kind: "weapon",
    category: "simple",
    range: Range.MELEE,
    damage: dmg("1d6", "bludgeoning"),
    properties: [
      {
        kind: "versatile",
        twoHandedDamage: "1d8",
      },
    ],
    tags: [],
    source: source("PHB", 149),
  },
  {
    id: "sickle",
    name: "Sickle",
    cost: cost("1 gp"),
    weight: 2,
    kind: "weapon",
    category: "simple",
    range: Range.MELEE,
    damage: dmg("1d4", "slashing"),
    properties: [
      { kind: "light" },
    ],
    tags: [],
    source: source("PHB", 149),
  },
  {
    id: "spear",
    name: "Spear",
    cost: cost("1 gp"),
    weight: 4,
    kind: "weapon",
    category: "simple",
    range: Range.MELEE,
    damage: dmg("1d6", "piercing"),
    properties: [
      {
        kind: "versatile",
        twoHandedDamage: "1d8",
      },
      {
        kind: "thrown",
        thrownRange: { normal: 20, long: 60 },
      },
    ],
    tags: [],
    source: source("PHB", 149),
  },
  {
    id: "lightCrossbow",
    name: "Light crossbow",
    cost: cost("25 gp"),
    weight: 5,
    kind: "weapon",
    category: "simple",
    range: { kind: "ranged", normal: 80, long: 320 },
    damage: dmg("1d8", "piercing"),
    properties: [
      { kind: "ammunition" },
      { kind: "loading" },
      { kind: "twoHanded" },
    ],
    tags: [],
    source: source("PHB", 149),
  },
  {
    id: "dart",
    name: "Dart",
    cost: cost("5 cp"),
    weight: 0.25,
    kind: "weapon",
    category: "simple",
    range: { kind: "ranged", normal: 20, long: 60 },
    damage: dmg("1d4", "piercing"),
    properties: [
      { kind: "finesse" },
      {
        kind: "thrown",
        thrownRange: { normal: 20, long: 60 },
      },
    ],
    tags: [],
    source: source("PHB", 149),
  },
  {
    id: "shortbow",
    name: "Shortbow",
    cost: cost("25 gp"),
    weight: 2,
    kind: "weapon",
    category: "simple",
    range: { kind: "ranged", normal: 80, long: 320 },
    damage: dmg("1d6", "piercing"),
    properties: [
      { kind: "ammunition" },
      { kind: "twoHanded" },
    ],
    tags: [],
    source: source("PHB", 149),
  },
  {
    id: "sling",
    name: "Sling",
    cost: cost("1 sp"),
    weight: 0,
    kind: "weapon",
    category: "simple",
    range: { kind: "ranged", normal: 30, long: 120 },
    damage: dmg("1d4", "bludgeoning"),
    properties: [
      { kind: "ammunition" },
    ],
    tags: [],
    source: source("PHB", 149),
  },
];
